apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: hubot
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: redis-role
  namespace: hubot
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    resourceNames:
    - redis-0
    - redis-1
    - redis-2
    verbs:
    - get
    - update
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: redis-role-binding
  namespace: hubot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redis-role
subjects:
  - kind: ServiceAccount
    name: redis
    namespace: hubot
---
apiVersion: v1
kind: Service
metadata:
  namespace: hubot
  name: redis
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:3.2-alpine
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              name: redis
